#------------------------------------------------------------------
# classify 서브패키지 — 수집 문서 C/S/O 자동 분류
#=> MpowerClassify가 뽑아 놓은 "정제 텍스트"와 "임베딩 벡터"를 소비해 문서를
#   기밀(C)/민감(S)/공개(O) 로 등급화하는 정책층이다. 추출·임베딩·데몬 코어는
#   건드리지 않고, 그 결과만 소비하는 소비자(consumer)로만 존재한다.
#
#   현재 구현 범위: L1 정규식 PII + L2 기밀사전 규칙 스캔(Signal A).
#   (Signal B 임베딩 라벨 전파, C 경로/ACL 은 후속 단계에서 추가)
#------------------------------------------------------------------

from .rules import (
    RuleSet,
    RuleHit,
    GradeSignal,
    StampSignal,
    SensitiveSignal,
    load_rules,
    validate_rules_data,
    format_violations,
    RuleSetValidationError,
    UnknownGradeError,
    GRADES,
    default_rules_path,
    default_seed_path,
    scan_text,
    superlinear_coverage,
    scan_stamp,
    scan_sensitive,
    max_grade,
)
from .context import NameSignal, scan_filename
from .fuse import FusionResult, fuse_signals
from .propagate import (
    EmbedSignal,
    SeedIndex,
    propagate,
    DoctypeEmbedSignal,
    DoctypeSeedIndex,
    propagate_doctype,
    MIN_SHARE_DOCTYPE,
)
from .engine import build_record, now_iso, propagate_records, propagate_doctype_records
from .axes import (
    TaxonomyNode,
    Taxonomy,
    load_taxonomy,
    validate_taxonomy_data,
    format_taxonomy_violations,
    TaxonomyValidationError,
    default_taxonomy_path,
    TAXONOMY_FILENAME,
    default_taxonomy_export_input_path,
    convert_mpower_json,
    write_taxonomy_yaml,
    export_from_mpower_json,
)
from .doc_rules import (
    ConflictSpec,
    DoctypeRule,
    DocRuleSet,
    load_doc_rules,
    validate_doc_rule_data,
    format_doc_rule_violations,
    DocRuleValidationError,
    default_doc_rules_path,
    DOC_RULE_FILENAME,
    build_scaffold,
    write_scaffold,
)
from .conflict import (
    MaxResolution,
    MultiResolution,
    resolve_max,
    resolve_multi,
    resolve_doctype,
    ensure_overridable_axis,
    AxisNotOverridableError,
    FIXED_STRATEGY_AXES,
)
from .doctype import DoctypeSignal, scan_doctype, merge_embed_candidates
from .summary import summarize_records

__all__ = [
    "RuleSet",
    "RuleHit",
    "GradeSignal",
    "StampSignal",
    "SensitiveSignal",
    "load_rules",
    "validate_rules_data",
    "format_violations",
    "RuleSetValidationError",
    "UnknownGradeError",
    "GRADES",
    "default_rules_path",
    "default_seed_path",
    "scan_text",
    "superlinear_coverage",
    "scan_stamp",
    "scan_sensitive",
    "max_grade",
    "NameSignal",
    "scan_filename",
    "FusionResult",
    "fuse_signals",
    "EmbedSignal",
    "SeedIndex",
    "propagate",
    "DoctypeEmbedSignal",
    "DoctypeSeedIndex",
    "propagate_doctype",
    "MIN_SHARE_DOCTYPE",
    "build_record",
    "now_iso",
    "propagate_records",
    "propagate_doctype_records",
    "TaxonomyNode",
    "Taxonomy",
    "load_taxonomy",
    "validate_taxonomy_data",
    "format_taxonomy_violations",
    "TaxonomyValidationError",
    "default_taxonomy_path",
    "TAXONOMY_FILENAME",
    "default_taxonomy_export_input_path",
    "convert_mpower_json",
    "write_taxonomy_yaml",
    "export_from_mpower_json",
    "ConflictSpec",
    "DoctypeRule",
    "DocRuleSet",
    "load_doc_rules",
    "validate_doc_rule_data",
    "format_doc_rule_violations",
    "DocRuleValidationError",
    "default_doc_rules_path",
    "DOC_RULE_FILENAME",
    "build_scaffold",
    "write_scaffold",
    "MaxResolution",
    "MultiResolution",
    "resolve_max",
    "resolve_multi",
    "resolve_doctype",
    "ensure_overridable_axis",
    "AxisNotOverridableError",
    "FIXED_STRATEGY_AXES",
    "DoctypeSignal",
    "scan_doctype",
    "merge_embed_candidates",
    "summarize_records",
]
